name: k8s-cluster
description: Create Kubernetes cluster with sensible defaults
version: 0.0.1
guides:
  - files:
      - LICENSE.md
    actions:
      - rename:
          pattern: '{{.Context.Source.Name}}/LICENSE.md'
          with: '{{.Input.name}}/LICENSE.md'
prompts:
  - name: name
    message: Provide a name for the kubernetes cluster
    default: systems
  - name: organizationName
    message: Organization Name
    default: organization
  - name: provider
    message: Choose provider
    default: digitalocean
    kind: select
    choices:
      - digitalocean
      - aws
