name: digitalocean
description: Create Kubernetes cluster with sensible defaults in digital ocean
version: 0.0.1
guides:
  - files:
      - '.envrc.sample'
    actions:
      - rename:
          pattern: '.envrc.sample'
          with: '.envrc'
      - replace:
          pattern: YOUR DIGITAL OCEAN ACCESS TOKEN WITH READ/WRITE
          with: '{{.Input.doToken}}'
      - replace:
          pattern: ADMIN PASSWORD FOR GRAFANA
          with: '{{.Input.grafanaAminPassword}}'
      - replace:
          pattern: ADMIN PASSWORD FOR JENKINS
          with: '{{.Input.jenkinsAdminPassword}}'
  - files:
      - '*'
    actions:
      - rename:
          pattern: digitalocean
          with: '{{.Input.name}}'
      - replace:
          pattern: (?i)systems
          with: '{{.Input.name}}'
      - replace:
          pattern: k8s-cluster
          with: '{{.Input.name}}'
      - replace:
          pattern: (?i)organization-name
          with: '{{.Input.organizationName}}'
      - replace:
          pattern: "10.12.0.0/16"
          with: '{{.Input.podCIDR}}'
      - replace:
          pattern: "10.13.0.0/16"
          with: '{{.Input.serviceCIDR}}'
      - replace:
          pattern: blr1
          with: '{{.Input.region}}'
      - replace:
          pattern: s-2vcpu-2gb
          with: '{{.Input.primarySize}}'
      - replace:
          pattern: s-4vcpu-8gb
          with: '{{.Input.nodePoolSize}}'
prompts:
  - name: podCIDR
    message: POD CIDR range
    default: 10.12.0.0/16
  - name: serviceCIDR
    message: Service CIDR range
    default: 10.13.0.0/16
  - name: region
    message: Region
    kind: select
    choices:
      - ams2
      - ams3
      - blr1
      - fra1
      - lon1
      - nyc1
      - nyc2
      - nyc3
      - sfo1
      - sfo2
      - sfo3
      - sgp1
      - tor1
    default: blr1
  - name: primarySize
    message: Choose machine type for primary nodes
    kind: select
    choices:
      - 16gb
      - 1gb
      - 2gb
      - 32gb
      - 48gb
      - 4gb
      - 512mb
      - 64gb
      - 8gb
      - c-16
      - c-2
      - c-32
      - c-4
      - c-8
      - c2-16vcpu-32gb
      - c2-2vcpu-4gb
      - c2-32vpcu-64gb
      - c2-4vpcu-8gb
      - c2-8vpcu-16gb
      - g-16vcpu-64gb
      - g-2vcpu-8gb
      - g-32vcpu-128gb
      - g-40vcpu-160gb
      - g-4vcpu-16gb
      - g-8vcpu-32gb
      - gd-16vcpu-64gb
      - gd-2vcpu-8gb
      - gd-32vcpu-128gb
      - gd-40vcpu-160gb
      - gd-4vcpu-16gb
      - gd-8vcpu-32gb
      - m-128gb
      - m-16gb
      - m-16vcpu-128gb
      - m-1vcpu-8gb
      - m-224gb
      - m-24vcpu-192gb
      - m-2vcpu-16gb
      - m-32gb
      - m-32vcpu-256gb
      - m-4vcpu-32gb
      - m-64gb
      - m-8vcpu-64gb
      - m3-16vcpu-128gb
      - m3-24vcpu-192gb
      - m3-2vcpu-16gb
      - m3-32vcpu-256gb
      - m3-4vcpu-32gb
      - m3-8vcpu-64gb
      - m6-16vcpu-128gb
      - m6-24vcpu-192gb
      - m6-2vcpu-16gb
      - m6-32vcpu-256gb
      - m6-4vcpu-32gb
      - m6-8vcpu-64gb
      - s-12vcpu-48gb
      - s-16vcpu-64gb
      - s-1vcpu-1gb
      - s-1vcpu-2gb
      - s-1vcpu-3gb
      - s-20vcpu-96gb
      - s-24vcpu-128gb
      - s-2vcpu-2gb
      - s-2vcpu-4gb
      - s-32vcpu-192gb
      - s-3vcpu-1gb
      - s-4vcpu-8gb
      - s-6vcpu-16gb
      - s-8vcpu-16gb
      - s-8vcpu-32gb
      - so-16vcpu-128gb
      - so-24vcpu-192gb
      - so-2vcpu-16gb
      - so-32vcpu-256gb
      - so-4vcpu-32gb
      - so-8vcpu-64gb
      - so1_5-16vcpu-128gb
      - so1_5-24vcpu-192gb
      - so1_5-2vcpu-16gb
      - so1_5-32vcpu-256gb
      - so1_5-4vcpu-32gb
      - so1_5-8vcpu-64gb
    default: s-2vcpu-2gb
  - name: nodePoolSize
    message: Choose machine type for the default node pools
    kind: select
    choices:
      - 16gb
      - 1gb
      - 2gb
      - 32gb
      - 48gb
      - 4gb
      - 512mb
      - 64gb
      - 8gb
      - c-16
      - c-2
      - c-32
      - c-4
      - c-8
      - c2-16vcpu-32gb
      - c2-2vcpu-4gb
      - c2-32vpcu-64gb
      - c2-4vpcu-8gb
      - c2-8vpcu-16gb
      - g-16vcpu-64gb
      - g-2vcpu-8gb
      - g-32vcpu-128gb
      - g-40vcpu-160gb
      - g-4vcpu-16gb
      - g-8vcpu-32gb
      - gd-16vcpu-64gb
      - gd-2vcpu-8gb
      - gd-32vcpu-128gb
      - gd-40vcpu-160gb
      - gd-4vcpu-16gb
      - gd-8vcpu-32gb
      - m-128gb
      - m-16gb
      - m-16vcpu-128gb
      - m-1vcpu-8gb
      - m-224gb
      - m-24vcpu-192gb
      - m-2vcpu-16gb
      - m-32gb
      - m-32vcpu-256gb
      - m-4vcpu-32gb
      - m-64gb
      - m-8vcpu-64gb
      - m3-16vcpu-128gb
      - m3-24vcpu-192gb
      - m3-2vcpu-16gb
      - m3-32vcpu-256gb
      - m3-4vcpu-32gb
      - m3-8vcpu-64gb
      - m6-16vcpu-128gb
      - m6-24vcpu-192gb
      - m6-2vcpu-16gb
      - m6-32vcpu-256gb
      - m6-4vcpu-32gb
      - m6-8vcpu-64gb
      - s-12vcpu-48gb
      - s-16vcpu-64gb
      - s-1vcpu-1gb
      - s-1vcpu-2gb
      - s-1vcpu-3gb
      - s-20vcpu-96gb
      - s-24vcpu-128gb
      - s-2vcpu-2gb
      - s-2vcpu-4gb
      - s-32vcpu-192gb
      - s-3vcpu-1gb
      - s-4vcpu-8gb
      - s-6vcpu-16gb
      - s-8vcpu-16gb
      - s-8vcpu-32gb
      - so-16vcpu-128gb
      - so-24vcpu-192gb
      - so-2vcpu-16gb
      - so-32vcpu-256gb
      - so-4vcpu-32gb
      - so-8vcpu-64gb
      - so1_5-16vcpu-128gb
      - so1_5-24vcpu-192gb
      - so1_5-2vcpu-16gb
      - so1_5-32vcpu-256gb
      - so1_5-4vcpu-32gb
      - so1_5-8vcpu-64gb
    default: s-4vcpu-8gb
  - name: doToken
    message: Digitalocean token
    kind: password
  - name: grafanaAminPassword
    message: Grafana admin password
    kind: password
  - name: jenkinsAdminPassword
    message: Jenkins admin password
    kind: password
when:
  all:
    - input: '{{.Input.provider}}'
      condition: '=='
      value: digitalocean
